# Uncomment this line to define a global platform for your project
# platform :ios, ’7.0’

target 'FacebookIntegrationDemo' do

pod 'Reachability'
pod 'Facebook-iOS-SDK'
pod 'Parse'
pod 'ParseFacebookUtils'
pod 'SDWebImage'
pod 'Reachability'

end

target 'FacebookIntegrationDemoTests' do

end

